# Generated by Django 2.2.1 on 2020-02-28 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=25)),
                ('food_des', models.TextField(max_length=25)),
                ('food_in', models.CharField(max_length=25)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
